### ISSUE TITLE
Editing the name of a saved chat tab (keypress) kills the UI

### ISSUE THREAD

**Issue by DennisRas** [rhymu8354/OmniaRegna#122]
**Screenshot:**  
![](https://i.imgur.com/BtYynau.png)

**Action:**  
Any keypress

**Error log:**
> react-dom.production.min.js:4408 TypeError: Cannot read property 'filter' of undefined
>     at ProfilePanel.js:261
>     at Array.map (<anonymous>)
>     at ProfilePanel.js:252
>     at Zr (react-dom.production.min.js:3274)
>     at As (react-dom.production.min.js:3745)
>     at Ds (react-dom.production.min.js:3957)
>     at Vo (react-dom.production.min.js:5514)
>     at Ho (react-dom.production.min.js:5536)
>     at Pa (react-dom.production.min.js:5958)
>     at Oa (react-dom.production.min.js:5925)

**Comment by rhymu8354** [comment]
Oh cool, I was wondering how this was happening.

**Comment by rhymu8354** [comment]
The problem was poor design in React/Redux state regarding player profile information.

The work-around for now is separate the current and new names for a tab, and keep track of the selected tab by index, and not by name.

**Comment by rhymu8354** [comment]
Pushed to production.
