### ISSUE TITLE
Keybind combinations/modifiers activate the regular keybinds ingame

### ISSUE THREAD

**Issue by DennisRas** [rhymu8354/OmniaRegna#126]
Example: CTRL + C to copy text opens up Chat

My suggestion is to disable the keybind behaviour ingame when modifiers (ctrl, shift, alt, cmd etc.) are being used, since some keybind combinations are browser/OS specific (such as copying text in the chat).

**Comment by rhymu8354** [comment]
The problem was the stage middleware had an onKeyDown which disregarded altKey, ctrlKey, and metaKey.

The solution is to ignore actions if altKey, ctrlKey, or metaKey is set on the key that was pressed.

**Comment by rhymu8354** [comment]
Pushed to production.
