### ISSUE TITLE
You can ignore someone already ignored

### ISSUE THREAD

**Issue by DennisRas** [rhymu8354/OmniaRegna#134]
Context menu isn't aware of whether the player is already ignored:

![](https://i.imgur.com/dfMfCaK.png)

**Comment by rhymu8354** [comment]
I fixed one part of this issue.

There was problem that there was no input validation on the new chat ignore input element.

The solution was to add input validation.

There is still the problem that you can add the same name to the ignore list twice via the context menu.

**Comment by rhymu8354** [comment]
I fixed the other part of the issue.

The problem was the ignore/whisper options disregarded whether or not the subject was being ignored.

The solution is to not provide the ignore/whisper options if the subject is ignored.

**Comment by rhymu8354** [comment]
Pushed to production.
