### ISSUE TITLE
I seemed to go into the admin panel

### ISSUE THREAD

**Issue by ProfElements** [rhymu8354/OmniaRegna#195]
![Capture](https://user-images.githubusercontent.com/43350117/62843314-a2846e80-bc7e-11e9-84f5-2abfeb2ff20d.PNG)

I absolutely don't know how or why this happened >> seems like it recognized my login though its on a a different browser

**Comment by rhymu8354** [comment]
This happens right now if you accidentally drop something onto the area marked with a red dashed line and the word "Admin":

![image](https://user-images.githubusercontent.com/41497796/63305828-34066880-c29d-11e9-97b4-6b06bd40cf45.png)

I've been meaning to hide this box by default but haven't gotten around to it.

Anyway, things should go back to normal if you press the "LogOut" button and then log back in.
