### ISSUE TITLE
Chat scrolling gets broken sometimes

### ISSUE THREAD

**Issue by rhymu8354** [rhymu8354/OmniaRegna#203]
This was reported in the in-game tickets 580 and 597.

580:

When In fight while attacking the "dialog" section is not scrolling to the bottom. Let's say I need to attack 10 times, then I'd need to scroll down the dialog section because it's stuck at the position it was before I attack
It could be scrolled automatically :)
( Sorry if not clear! )

597: 

The dialog for attacking commands and feedback from attacking does not scroll the chat window down to the bottom. This then makes it so that new chat messages and other messages that enter the chat window do not update the position.

To reproduce:

Create attacking chat feedback by attacking a monster
Have one or more chat messages sent by Golem or another player
The chat window will not move

**Comment by asquared31415** [comment]
When in this state, when the affected player chats, it scrolls to the bottom of the attack messages, but the just added chat message is obscured still, and new messages will not scroll it.

**Comment by asquared31415** [comment]
This bug appears to be resolved in the latest front end version on 25 Feb, 2020

**Comment by rhymu8354** [comment]
It's still possible to break this, but only by manually resizing the window.  I think this is ok for now.
