### ISSUE TITLE
Link to Github issue tracker in-game

### ISSUE THREAD

**Issue by rhymu8354** [rhymu8354/OmniaRegna#24]
This is in-game ticket #236: [Liquidor]

Link to GH Issue Tracker ingame

**Comment by rhymu8354** [comment]
Also in-game ticket #268: [Neui]

In-Game issue to Github issue mapping, like there is an extra "column" in the ticket details containing a link to the github issue version.

**Comment by DennisRas** [comment]
Use query parameters to prefill the issue with Account details:  
https://help.github.com/en/articles/about-automation-for-issues-and-pull-requests-with-query-parameters#supported-query-parameters

**Comment by rhymu8354** [comment]
PWS also gave me the link in live chat today:

https://help.github.com/en/github/managing-your-work-on-github/about-automation-for-issues-and-pull-requests-with-query-parameters

**Comment by rhymu8354** [comment]
[10:29] PianoBoxer: @rhymu8354 Could you have your backend open an issue on GitHub automatically when a user creates a in-game ticket? I guess it would become a little complicated on what to do when the GitHub issue is commented/closed etc (Should the in-game ticket track the GitHub issue (and the other way around).

**Comment by rhymu8354** [comment]
The ticket display now includes a "GitHub" field which is a link if filled in, and allows the admin to set, edit, or remove the link.
