### ISSUE TITLE
[Feature Request] Weapon slot

### ISSUE THREAD

**Issue by asquared31415** [rhymu8354/OmniaRegna#252]
A weapon slot for the player might be useful.  It would be one slot that would be dedicated for a weapon.  It would be the only slot used in combat, clarifying which weapon is used if a player has more than one in their inventory.  It could have a fist icon in the background to represent that without a weapon equipped, your fists are used in combat.  This would also free up a player inventory slot for items such as gold or limited edition fireworks, or eventually other items.

**Comment by rhymu8354** [comment]
Excellent point.  I thought there was a ticket already for this request, but turns out there wasn't.

**Comment by rhymu8354** [comment]
This was actively worked on during today's stream, and is still a work in progress.

**Comment by asquared31415** [comment]
The equipment system has this feature, and more

**Comment by rhymu8354** [comment]
Yes, I forgot to go back and update this ticket.  Thanks asquared31415!
